$(".weekly").addClass("click");
$(".daily").click(function(){
  $(".work-hr").text("5hrs");
  $(".last-work").text("Yesterday - 7hrs");
  $(".play-hr").text("1hr");
  $(".last-play").text("Yesterday - 2hrs");
  $(".study-hr").text("0hr");
  $(".last-study").text("Yesterday - 1hr");
  $(".exercise-hr").text("1hr");
  $(".last-exercise").text("Yesterday - 1hr");
  $(".social-hr").text("1hr");
  $(".last-social").text("Yesterday - 3hrs");
  $(".self-hr").text("0hr");
  $(".last-self").text("Yesterday - 1hr");
  $(".daily").addClass("click");
  $(".weekly").removeClass("click");
  $(".monthly").removeClass("click");
});
$(".weekly").click(function(){
  $(".work-hr").text("32hrs");
  $(".last-work").text("Last Week - 32hrs");
  $(".play-hr").text("10hrs");
  $(".last-play").text("Last Week - 8hrs");
  $(".study-hr").text("4hrs");
  $(".last-study").text("Last Week - 7hrs");
  $(".exercise-hr").text("4hrs");
  $(".last-exercise").text("Last Week - 5hrs");
  $(".social-hr").text("5hrs");
  $(".last-social").text("Last Week - 10hrs");
  $(".self-hr").text("2hrs");
  $(".last-self").text("Last Week - 2hrs");
  $(".daily").removeClass("click");
  $(".weekly").addClass("click");
  $(".monthly").removeClass("click");
});
$(".monthly").click(function(){
  $(".work-hr").text("103hrs");
  $(".last-work").text("Last Month - 128hrs");
  $(".play-hr").text("23hrs");
  $(".last-play").text("Last Month - 29hrs");
  $(".study-hr").text("13hrs");
  $(".last-study").text("Last Month - 19hrs");
  $(".exercise-hr").text("11hrs");
  $(".last-exercise").text("Last Month - 18hrs");
  $(".social-hr").text("21hrs");
  $(".last-social").text("Last Month - 23hrs");
  $(".self-hr").text("7hrs");
  $(".last-self").text("Last Month - 11hrs");
  $(".daily").removeClass("click");
  $(".weekly").removeClass("click");
  $(".monthly").addClass("click");
});
